import type { Metadata } from 'next';
import AuthProvider from '@/context/AuthProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'full stack  App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={` antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
